
version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "80:80"
    networks:
      - proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

networks:
  proxy:
    external: true
    name: "8651f5efd1b17dbd02faad559c12fa3d36bdae18d720c4de3b6cf6627db9cec6_proxy"
volumes:
  certificates:
